version: '3'

services:
  api:
    restart: always
    build: ./
    ports:
      - 27004:27004
    depends_on:
      - mysql
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_DATABASE=PixelSchool
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
 